Add code formatting check step to Maven workflow
Add a step to check for code formatting errors in the workflow.

diff --git a/.github/workflows/maven-pr.yml b/.github/workflows/maven-pr.yml
--- a/.github/workflows/maven-pr.yml
+++ b/.github/workflows/maven-pr.yml
@@ -35,3 +35,12 @@ jobs:
         cache: maven
     - name: Build with Maven
       run: mvn -B package --file pom.xml
+
+    - name: Check for wrong code formatting
+      run: |
+          if [[ -n $(git status --porcelain) ]]; then
+              echo "Code formatting errors"
+              echo "----------------------"
+              git diff
+              exit 1
+          fi
